Document: git-wiki
Title: Debian git-wiki Manual
Author: <insert document author here>
Abstract: This manual describes what git-wiki is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/git-wiki/git-wiki.sgml.gz

Format: postscript
Files: /usr/share/doc/git-wiki/git-wiki.ps.gz

Format: text
Files: /usr/share/doc/git-wiki/git-wiki.text.gz

Format: HTML
Index: /usr/share/doc/git-wiki/html/index.html
Files: /usr/share/doc/git-wiki/html/*.html
